# 1. La URL del Pooler en modo Session que acabas de copiar
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?user=postgres.upnjrtadljuhdztpmnvl&password=[Contraseña Aqui]

# 4. Configuraciones de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true