# 1. La URL limpia (SIN usuario ni contraseña al final)
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres

# 2. Tu usuario completo
spring.datasource.username=postgres.upnjrtadljuhdztpmnvl

# 3. Tu contraseña (dejamos un texto falso por seguridad para GitHub)
spring.datasource.password=TU_CONTRASEÑA_AQUI

# 4. Configuraciones de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.datasource.hikari.maximum-pool-size=5